### ISSUE TITLE
Removing debug console.log in fetch requests

### ISSUE THREAD

**Issue by PorthoGamesBR** [PorthoGamesBR/my-notes#13]
There is a lot of console.log functions in the fetch request in the getNotes custom hook, that were added to debug and see if the data was correct but now are just poluting the console. It would be good to remove them.

**Comment by VanshVg** [comment]
Hey @PorthoGamesBR Just need to remove getNotes console.log or from other functions too?

**Comment by SamMrach** [comment]
@PorthoGamesBR  please assign it to me.

**Comment by PorthoGamesBR** [comment]
> Hey @PorthoGamesBR Just need to remove getNotes console.log or from other functions too?

Just from getNotes for now

**Comment by PorthoGamesBR** [comment]
> @PorthoGamesBR I opened a draft pull request with my solution, I'd appreciate it if you could review the request.
> Have a great day everyone!

Ok, i will review it later and send you the feedback
