### ISSUE TITLE
New note button is transparent

### ISSUE THREAD

**Issue by PorthoGamesBR** [PorthoGamesBR/my-notes#26]
It is kinda ugly, specially on smaller screens where the button stays on top of some of the text. It would be good for the Circle Container to have a background color, i think white would be good

**Comment by PorthoGamesBR** [comment]
> Hi, Can you please assign this issue to me?
> 
> Thanks!

There you go @this-is-sky

**Comment by this-is-sky** [comment]
Thanks!

**Comment by PorthoGamesBR** [comment]
@this-is-sky If you having any problems, just send me a message here or private.

**Comment by this-is-sky** [comment]
Yeah, Can you please elaborate more, what type of colour and background you want?

**Comment by PorthoGamesBR** [comment]
@this-is-sky A white background should be good

**Comment by SshibamDebnathh** [comment]
is this issue still open?

**Comment by SshibamDebnathh** [comment]
attach a screenshot of the specific issue?

**Comment by PorthoGamesBR** [comment]
> is this issue still open?

yes, it is. I could have solved it already but i let this kind of issue for people new to GitHub to solve, since it's very simple.

**Comment by PorthoGamesBR** [comment]
> attach a screenshot of the specific issue?
![image](https://github.com/PorthoGamesBR/my-notes/assets/84247243/817cb3ac-49d2-4fe9-9012-86f8df1757e9)
