### ISSUE TITLE
Server is off but app operates as normal

### ISSUE THREAD

**Issue by PorthoGamesBR** [PorthoGamesBR/my-notes#3]
So, even if the database is not connected, the app continues to run as if nothing was happening. I understand that this is good as the front end should not be dependent on the back end, but it's frustating that you edit everything only to discover the server was offline.
If the app could at least alert that the connection with the server was not sucessfull, this wouldnt be a problem; Just ping the server adress and alert the user if the ping has no response.

**Comment by Rishav13773** [comment]
@PorthoGamesBR  I agree that the app should warn us about the lost server connection. I think it can be handled in two ways.

**1. Initial Stage -** The frontend should send request to backend to check if the server is up and running, if not it should be display some sort of alert when user first visit the web app.

**2. Later Stage -** Ensure that the app gracefully handles the situation when the connection is lost while the user is actively using it. For instance, allow users to continue working offline and display a reminder to sync their changes once the server connection is restored.

**Comment by PorthoGamesBR** [comment]
That´s a good sugestion, for the app to synch once the connection is up again. Now, should the app keep trying to reconect automaticaly or should it wait for a user input like a button or something like that?

Since the idea of this app is to run on a local server, i think waiting for the input is the best solution since the user will be the one to boot up the server again.

**Comment by PorthoGamesBR** [comment]
And i think an alert component should do the trick. Bootstrap for styling, since it already has a floating alert styling. Just decide between red or yellow, but since this is not a bug in the app itself, yellow should be better.

**Comment by Rishav13773** [comment]
@PorthoGamesBR Well, I think a reconnect to the server button would be interesting in my opinion as the user working on app. We can save user progress in local storage, and if the server is reconnected we can send the data. As for reconnecting on input will that not create too many server request while user is working ?

**Comment by PorthoGamesBR** [comment]
@Rishav13773 Since the main idea of this app is to have local storage (The idea is to have a local server), it fits pretty well to save the changes in the browser local storage.
The reconnect on input would be a button that the user can press to try to connect to the server, so the ammount of requests would be decided on how much the user pressed the button. But since the main idea is to have a local server, i dont think ammount of requests by the user will be a  big problem.
